variables:
  managedIdentityClientId: 'c7516409-8113-41d8-b994-6201c16a543a'
  subscriptionId: 'f8ae64a8-decc-4be8-9dbe-e14eba877219'
  tenantId: '29828deb-3c61-469d-a759-e2726411fdbe'

trigger:
  - main

pool:
  name: iac-poc-pool

steps:
  - checkout: self

  - script: |
      echo "Terraform init"
      export ARM_USE_MSI=true
      export ARM_CLIENT_ID=$(managedIdentityClientId)
      terraform init
    displayName: 'Initialize Terraform'
    workingDirectory: terraform
    env:
      ARM_SUBSCRIPTION_ID: $(subscriptionId)
      ARM_TENANT_ID: $(tenantId)

  - script: |
      echo "Terraform apply"
      export ARM_USE_MSI=true
      export ARM_CLIENT_ID=$(managedIdentityClientId)
      terraform plan -out=tfplan
    displayName: 'Plan Terraform ASB Deployment'
    workingDirectory: terraform
    env:
      ARM_SUBSCRIPTION_ID: $(subscriptionId)
      ARM_TENANT_ID: $(tenantId)

  - script: |
      terraform apply -auto-approve tfplan
    displayName: 'Apply Terraform ASB Deployment'
    workingDirectory: terraform