trigger:
  - main

pool:
  name: iac-poc-pool

variables:
  # Function app name
  functionAppName: 'asb-test-function-app'
  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      options: '-DskipTests'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'deploy-functions-pipeline-service-connection' # This still needs to be a valid service connection.
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az functionapp deployment source config-zip \
          --name $(functionAppName) \
          --resource-group <Resource-Group-Name> \
          --src $(workingDirectory)/target/azure-functions/$(functionAppName)/*.zip
