trigger:
  - main

pool:
  name: iac-poc-pool

variables:
  # Function app name
  functionAppName: 'asb-test-function-app'
  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)'

steps:

    - script: |
      # Downloading the latest version of Maven, change URL if necessary
       wget https://archive.apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
      
        # Extracting Maven to the /opt directory
       sudo tar -xvzf apache-maven-*-bin.tar.gz -C /opt
      
        # Renaming the extracted folder to a generic name to avoid changing paths in the future
       sudo mv /opt/apache-maven-* /opt/maven
      
        # Setting up environment variables
        MAVEN_HOME=/opt/maven
        PATH=$PATH:$MAVEN_HOME/bin
        echo "export MAVEN_HOME=/opt/maven" | sudo tee -a /etc/profile.d/maven.sh
        echo "export PATH=$PATH:$MAVEN_HOME/bin" | sudo tee -a /etc/profile.d/maven.sh
        
        # Loading the new environment variables
        source /etc/profile.d/maven.sh
      displayName: 'Install latest Maven'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'deploy-functions-pipeline-service-connection' # This still needs to be a valid service connection.
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az functionapp deployment source config-zip \
            --name $(functionAppName) \
            --resource-group <Resource-Group-Name> \
            --src $(workingDirectory)/target/azure-functions/$(functionAppName)/*.zip
