trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Function app name
  functionAppName: 'asb-test-function-app'
  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)'

steps:
  - task: UseJava@1
    inputs:
      version: '17'
      jdkArchitectureOption: 'x64'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      options: '-DskipTests'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  # Replace AzureFunctionApp task with Azure CLI script
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Name of the Azure Resource Manager service connection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az functionapp deploy --name $(functionAppName) --resource-group <Resource-Group-Name> --src-path $(workingDirectory)/target/azure-functions/$(functionAppName)/* --type zip