trigger:
  - main

pool:
  name: iac-poc-pool

steps:
  - checkout: self

  - script: |
      terraform init
    displayName: 'Initialize Terraform'
    workingDirectory: terraform

  - script: |
      terraform destroy -auto-approve
    displayName: 'Destroy Terraform ASB Resources'
    workingDirectory: terraform